package com.gtnewhorizon.newgunrizons.state;

public enum RenderableState {
   NORMAL,
   RUNNING,
   ZOOMING,
   SHOOTING,
   AUTO_SHOOTING,
   RECOILED,
   ZOOMING_SHOOTING,
   ZOOMING_RECOILED,
   RELOADING,
   UNLOADING,
   LOAD_ITERATION,
   LOAD_ITERATION_COMPLETED,
   ALL_LOAD_ITERATIONS_COMPLETED,
   EJECT_SPENT_ROUND,
   MODIFYING,
   SAFETY_PIN_OFF,
   STRIKER_LEVER_OFF,
   THROWING,
   THROWN;
}
